
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { Toaster } from "@/components/ui/Toaster"
import Providers from "@/components/Providers"
import Sidebar from './components/Sidebar'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode
  authModal: React.ReactNode
}) {

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body 
        className='min-h-screen bg-slate-50 dark:bg-dark text-dark dark:text-slate-50 antialiased flex flex-col'
        
      >
      <Providers>
          <Navbar />
          <div className='flex w-high'>
            <Sidebar /> 
            {authModal}
            <div className='w-full mt-20 p-8'>
              {children}
            </div>
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
